### ISSUE TITLE
Store data on the user's device

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#109]

**Comment by Gudahtt** [comment]
@rekmarks Is this closed by https://github.com/MetaMask/snaps-skunkworks/pull/134 ?

**Comment by rekmarks** [comment]
Ah, no, but I'd argue that it is closed by https://github.com/MetaMask/snaps-skunkworks/pull/135

**Comment by Gudahtt** [comment]
Oh, sorry! That's the one I meant to link
