### ISSUE TITLE
Add Snap request processing queue

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#117]
Once we have established a configurable Snap concurrency limit (#59), we should implement a queue for JSON-RPC requests for snaps that are stopped. As running snaps are stopped and concurrency "slots" (we have yet to pick a word for this) become available, snaps with queued requests should be started in a FIFO manner, and receive all of their requests once booted.

**Comment by FrederikBolding** [comment]
Related to #245 ?

**Comment by hmalik88** [comment]
Yes, this looks to be a dupe. @rekmarks?

**Comment by ritave** [comment]
Browser's event queue handles this problem for us automatically today.

While we could consider adding a limit of waiting requests, this is not part of this issue so I'm closing it.
