### ISSUE TITLE
Refactor proposal: Make an object to represent a single snap

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/snaps-skunkworks#208]
The `SnapsController` (and execution environment services) has a series of maps that each point to the snaps that it manages.

This means when we want to do things like unregister event listeners, we end up going down each of these maps, and unsetting them, and in general it means that data that really is per-snap is sprawled across the code that applies to the entire snap controller.

I think there is a cleanup/refactor we could do where we create a `Snap` class that represents a single initialized snap. This would allow us to keep initialization and teardown steps very neatly isolated to the object being handled, and makes it easier to make further changes to our model (for example, if we decide to initialize a snap per persona).

This isn't urgent, but it's a refactor that I've consistently found myself wanting.

**Comment by FrederikBolding** [comment]
Not sure how feasible it is to use classes given that the state management requires objects that enter state to be serializable. 

After speaking with @rekmarks, I've opened a PR #229 which combines the maps used in `SnapsController` to a single map. Not entirely sure this is what was intended originally with this issue. But in my opinion it is at least a bit cleaner using 1 map over 3 😄
