### ISSUE TITLE
Specify Execution Environment JSON-RPC API in OpenRPC

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#22]
There is a set of JSON-RPC methods that we expect every conceivable execution environment to implement. This includes:

- `executePlugin`, formerly known as `installPlugin`, for executing plugin source code
- `handshake`, formerly known as `ping`, for confirming that a connection has been established with the worker
- `pluginRpc`, for routing RPC messages to a plugin running in the execution environment

**Comment by shanejonas** [comment]
fixed in #23
