### ISSUE TITLE
Allow snaps to be updated

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#223]
We should introduce an `updateSnap`/`updateSnaps` method to the `SnapController` that updates the specified snap(s) from one version to another. We won't do anything about downgrades for now.

Snaps are expected to use SemVer, which informs how we handle updating. (The [`semver` npm package](https://www.npmjs.com/package/semver) should do everything we need.)

Here follows a non-exhaustive list of requirements for our update mechanism:
- A subject _may_ specify a version when it asks to connect to a snap. If the requested is installed, we find ourselves in one of two cases:
  - The snap is compatible per SemVer. Proceed with the connection request as normal.
  - The snap is not compatible per SemVer. In this case, we should ask the user to update. We may or may not let the user try to connect an incompatible snap, but UX questions of that nature are mostly out of scope for the implementation of the update mechanism itself. The important thing is that we give ourselves (and the user) the option to override SemVer if we want to.
- When a snap is updated:
  - We should first download the new version and perform the same verification that we do during normal installation. After verification, the new snap should be started for the first time, with its existing permissions and state retained.
  - We should provide a rollback mechanism. As the new version is installed and booted, we should take a snapshot of the existing state (if the snap has state management) and permissions and the old snap as it exists in `SnapController` state. We should retain the old snap in state for a configurable period of time, so that we can give the user the option to roll back if they want to.
    - We should also roll back automatically if the new snap fails to start or crashes after startup.

There are some outstanding questions to solve:
- What happens when the permissions differ between snap versions?
  - Permissions added by a new version are easy enough, but permissions _removed_ by a new version are more difficult to handle. Note that we want to let snaps request permissions dynamically, and that the rollback mechanism must take our solution into account.
  - If the PermissionController's interface doesn't support our needs here, we can modify it.
- How do we detect a crash on startup? Do we run the snap before letting it communicate with the outside world?

**Comment by ritave** [comment]
Work to be done:
- [ ] Create updateSnap function - #259 
- [ ] Try to update snap in processRequestedSnap when the current one doesn't match new semver range
- [ ] Add a rollback mechanism
  - [ ] Automatic rollback on update failure

**Comment by rekmarks** [comment]
Rollbacks are tracked in #618
