### ISSUE TITLE
Chrome Sandboxed page snaps execution environment

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/snaps-skunkworks#226]
We should create a snaps execution environment using the "Sandboxed page" feature of the Chrome extension API: https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/

Sandboxed pages can have their own CSP, so it's easier to enable `eval`. I am hoping they might be throttled separately from the extension process as well, which might result in increased performance over the web worker execution environment.

It does not appear that we can dynamically add sandboxed pages, but we could statically add one or multiple sandbox snap runners, and use them in the same manner as the web worker based snaps (where they have a fixed queue size, e.g. 10 running at once).

**Comment by Montoya** [comment]
We will not be pursuing this approach
