### ISSUE TITLE
Add snaps notification permission

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#230]
We should add a new restricted method, `snap_notify`, that allows snaps to notify users. The method should have a single object parameter with at least one property, `type`, which specifies the kind of notification that is being created. In addition, the object must have whatever fields are required to populate the content of the notification(s).

Exactly what this method will look like depends on the notifications we will support, and the content that they support. For now, and for the sake of simplicity, these notifications should be read-only, and probably only support a text message of whatever length can fit within the notification window.

Really, we have two possible types too choose from: native browser notifications and notifications inside the MetaMask UI. We can start with one or the other, or implement both at once.

### Requirements
- Method name: `snap_notify`
- Parameter: something like: `[{ type: string, message: string }]`
- Notifications must be rate limited.
  - This should be configurable by the host environment, and not hard-coded in the RPC method implementation itself.
  - The rate limiting could be per notification type or for all notifications, of all types.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/230?planning-poker) with ZenHub @Gudahtt @hmalik88 @ritave

**Comment by FrederikBolding** [comment]
@rekmarks Do we want to close this with #234?

**Comment by rekmarks** [comment]
@FrederikBolding, yeah, we can consider this closed!
