### ISSUE TITLE
Clean up SnapController logging

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#255]
We do a lot of `console` calls in the `SnapController`, mostly `.log()`. We should review these calls, get rid of the ones that aren't necessary, ensure that all log messages follow a standard format, and perhaps accept a log API via the constructor, such as the `loglevel` object used in the extension.

**Comment by FrederikBolding** [comment]
@rekmarks What is our definition of `necessary` here? How much logging do we really want to do? 🤔

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/255?planning-poker) with ZenHub @FrederikBolding @hmalik88 @ritave
