### ISSUE TITLE
Include `setInterval`/`clearInterval` as default endowments

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#299]
~Are there any additional concerns with these over `setTimeout`/`clearTimeout`?~

We concluded that there are no additional concerns with `setInterval`/`clearInterval` over `setTimeout`/`clearTimeout`. We should attenuate the interval functions in the same way that we do the timeouts, and add them as default endowments.

**Comment by ritave** [comment]
None more that I know of.

Interestingly `setTimeout` and `setInterval` use [eval behind the scenes](https://csplite.com/csp148/), but since it's run in SES context, it shouldn't matter for security purpouses.

**Comment by Montoya** [comment]
AFAIK there's no fundamental difference, if you let developers use a repeating setTimeout then it's the same thing.

**Comment by FrederikBolding** [comment]
I think intervals opens up a lot of interesting possibilities **if** they can keep running. The challenge here is fitting it with our current lambda-esque execution environment, right?

Example: check for gas prices every 2 minutes and notify me when they are below 20 GWEI

**Comment by rekmarks** [comment]
@FrederikBolding those concerns are what I'm trying to reason about. Since whether a snap is kept alive is wholly dependent on when it receives an RPC message, I don't think the interval functions pose any lifecycle-related risks. If we ever want to account for timeouts and intervals in some way with respect to lifecycle management, we should easily be able to modify our attenuated implementations to support that use case.

I'm gonna update the name of this issue and greenlight this.

**Comment by FrederikBolding** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/299?planning-poker) with ZenHub @rekmarks
