### ISSUE TITLE
Develop a set of recommendations for developers that rely on `XMLHttpRequest`

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#300]
We can't ship `XMLHttpRequest` support in the Snaps execution environment because we will one day run on platforms where it doesn't exist, such as Node.js, and it seems highly unlikely that we'd ever maintain a polyfill for it. Despite better alternatives existing literally everywhere, we still come across dependencies that use `XMLHttpRequest`, in particular `axios` and `cross-fetch` (for unknown reasons). Being network-related, these packages are often deep in a snap's dependency tree, and difficult to replace. We need a set of recommendations for snap developers that run into this problem. Ideally, those recommendations are something other than simply "get rid of `XMLHttpRequest`", but that may be the best we can do.

**Comment by FrederikBolding** [comment]
**cross-fetch**
Interestingly `cross-fetch` has a line which is commented out that allows it to use the native `fetch` API if present. So creating a patch for that is easier than expected: https://github.com/MetaMask/snaps-skunkworks/blob/dbf87a7a3cb95e803f91339aeff3a7c4549b6a94/patches/cross-fetch%2B3.1.5.patch
We may want to reach out and try to understand why they are choosing to not use this though, but at this point I don't see a reason as to not use the native fetch API when present.

**axios**
Probably a larger problem to solve for any dev that has it as a transitive dependency. However, it is potentially patchable via https://github.com/vespaiach/axios-fetch-adapter.

I've verified that other fetch libraries such as `isomorphic-fetch` and `isomorphic-unfetch` work fine with the current snaps platform and could be used as recommendations for patching or general usage.

I think overall the only thing we can do is to provide examples of how to patch out `XMLHttpRequest` for some of these large libraries and then keep adding to that list once we get more reports from devs.

**Comment by FrederikBolding** [comment]
Adding to the `cross-fetch` stuff we may want to recommend to bind it as well. That is needed for use in the MetaMask extension at least, but seems to not be an issue in snaps. 

Patch for that is here: https://github.com/MetaMask/snaps-skunkworks/blob/42fa8bbb6b82fd63dd4e10fdba1cdad09ef46571/patches/cross-fetch%2B3.1.5.patch

**Comment by FrederikBolding** [comment]
`axios-fetch-adapter` will not work in the current snaps execution environment and likely not in Node.js either. It uses globals that we currently don't expose (and don't seem to be available in Node.js) like: `Headers` and `Request`.
