### ISSUE TITLE
Allow code to be executed during state transition in SnapController

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-skunkworks#304]
#298 fixed a bug where a state transition outside one specific function caused bugs in crash handling. The bug can re-appear again when somebody uses `_transitionSnapState(snapId, SnapStatusEvent.crash)` outside of `stopSnap` again in the future. 

One solution would be to refactor state transitions in a way that code is executed during the transition itself after an event is called instead of in `stopSnap`

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/304?planning-poker) with ZenHub @FrederikBolding @hmalik88 @ritave
