### ISSUE TITLE
Comment stripping makes some bundles invalid

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#323]
I've seen this issue with multiple snaps at this point. The solution has just been to set `--strip=false`, we should investigate why this is happening and fix it.

**Comment by FrederikBolding** [comment]
This happens both in https://github.com/FrederikBolding/metamask-snap-bitcoin/tree/fb/port-to-latest and https://github.com/FrederikBolding/metamask-snap-polkadot/tree/fb/port-to-latest

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/323?planning-poker) with ZenHub @FrederikBolding @hmalik88 @ritave

**Comment by FrederikBolding** [comment]
> @FrederikBolding what errors are you getting exactly?

@rekmarks Running `mm-snap build` without `--strip=false` results in the build succeeding but failing at eval time due to the `bundle.js` being invalid. 

The exact error is: `SyntaxError [Error]: Unexpected end of input`

The broken bundle is `59153` lines while the actual working bundle is `86885` lines. So it seems a bunch of the bundle is erroneously removed.

**Comment by FrederikBolding** [comment]
Update: This occurs because `/** foo/* **/` is a valid comment, but `strip-comments` handles it wrongly.

**Comment by FrederikBolding** [comment]
Proposed fix here: https://github.com/NodeFactoryIo/strip-comments/pull/6

Another thing to consider is that comment stripping is very slow for larger bundles, do we still want it to be enabled by default 🤔
