### ISSUE TITLE
ses/lockdown mudule not found when running mm-snap build

### ISSUE THREAD

**Issue by arisrayelyan** [MetaMask/snaps-skunkworks#335]
Please refer this [link](https://github.com/MetaMask/snaps-skunkworks/blob/99566098d5ea066e248a77ea745da66200e244b2/packages/cli/src/cmds/eval/eval-worker.ts#L6)

Fixed it locally with changing

FROM
```
import 'ses/lockdown';
```

TO
```
import 'ses';
```

lockdown function will be available globally

Please check package documentation
https://github.com/endojs/endo/tree/master/packages/ses

My current Node Version was `12.11.0 `  as it required in snap documentation
My Os 
MacBook: Pro (14-inch, 2021)
Chip: Apple M1 Pro

**Comment by FrederikBolding** [comment]
Hi! Thanks for reporting this.

Do you have a repo where this can be reproduced? From looking at the `ses` source code it seems that the `ses/lockdown` alias still exists. 🤔 

Potentially regardless we may want to make a change for this, but it should be working with the current version.

**Comment by rekmarks** [comment]
@arisrayelyan thank you for creating this issue. Others have reported this, but we have yet to determine what's causing this. The `ses` package uses the package.json `exports` field to specify its various exports, and `/lockdown` is one such export.

Does this issue persist if you use Node 14 instead? We are about to deprecate Node 12 support since it is reaching EOL at the end of this month.

**Comment by arisrayelyan** [comment]
Hi @rekmarks, thanks for your message. The issue is **not** happening when I am changing my node version to v14 or v16 but with v12 it's throwing `Error: Cannot find module 'ses/lockdown'`. If you are going to deprecate v12 I think it will be fixed, also I saw you have updated node required version in [template-snap](https://github.com/MetaMask/template-snap).

**Comment by rekmarks** [comment]
Thank you for that answer @arisrayelyan. We are indeed deprecating our Node 12 support, which has reached its EOL anyway. Ref: https://nodejs.org/en/about/releases/

![image.png](https://images.zenhubusercontent.com/5b182d0580f2a54a594714b0/f12b4a34-c37e-43aa-adca-bb1653d2f141)
