### ISSUE TITLE
snap_notify isn't available

### ISSUE THREAD

**Issue by paulfears** [MetaMask/snaps-skunkworks#344]
When I try to add the snap_notify permission I get this using snaps-cli 0.10.7

sentry-install.js:1 Error when adding snap. {
  "code": -32601,
  "message": "The method \"snap_notify\" does not exist / is not available.",
  "data": {
    "origin": "local:http://localhost:8081/",
    "requestedPermissions": {
      "snap_confirm": {},
      "snap_getBip44Entropy_283": {},
      "endowment:network-access": {},
      "snap_notify": {}
    }
  },

**Comment by FrederikBolding** [comment]
Hey there! 

You may be using an outdated version of MetaMask Flask. If you are building and running MM locally be sure to pull down the latest `develop`. If you are using the Chrome store version, be sure to check that it has been updated as well!

**Comment by rekmarks** [comment]
@paulfears did your issue persist after updating?

**Comment by paulfears** [comment]
Yes the issue did after updating from the chrome store. For my particular use case though it would be impractical to target a version of metamask flask that isn't on the chrome store, so I never tried downloading from the develop branch.

**Comment by rekmarks** [comment]
Copy that. Can you try using Node 14 and see if that resolves the issue?

**Comment by rekmarks** [comment]
Copy that, this should be resolved in an update that ships next week. We'll keep this issue open until we've confirmed that.

**Comment by paulfears** [comment]
Thank you

**Comment by paulfears** [comment]
Works great good work
