### ISSUE TITLE
Installation should be reject with correct error if Snap ID is invalid 

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#347]
As of Flask `10.11.4`, when MetaMask receives a request to install a snap with an invalid ID, the expect "invalid ID" error is thrown asynchronously, but the installation request is rejected with a different error that should never occur at runtime.

The error thrown asynchronously:
```
Error when adding snap. Error: Invalid snap id. Received: "@metamask/test-snap-error"
  at y.validateSnapId (background-1.js:7:144026)
  at y.add (background-1.js:7:143439)
  at y.processRequestedSnap (background-1.js:7:142270)
  at background-1.js:7:141574
  at Array.map (<anonymous>)
  at y.installSnaps (background-1.js:7:141392)
  at Object.n.handleInstallSnaps (background-3.js:33:55937)
  at implementation (background-2.js:10:94494)
  at async background-1.js:1:176874
```

The returned error:
```
{
  code: -32600,
  message: "The snap \"@metamask/test-snap-error\" is not installed. This is a bug, please report it.",
}
```

(On a related note, why are we using that code instead of -32603 "internal error"?)

**Comment by FrederikBolding** [comment]
@rekmarks I can't reproduce this on `develop`. I get 

```
{
  code: -32603
  data: {originalError: {…}}
  message: "Invalid snap id. Received: \"@metamask/test-snap-error\""
}
```

However, the other error you are mentioning is thrown if you try to invoke a non-installed snap.

**Comment by FrederikBolding** [comment]
Do we want to check for snap id validity before trying to invoke perhaps?

**Comment by rekmarks** [comment]
I was wrong and will open a new issue.
