### ISSUE TITLE
Do not prompt for existing permissions during `wallet_enable`

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#348]
Installing a snap via `wallet_enable` currently consists of three steps under the hood, presented to the user as two confirmations:
1. Adding permissions for the site to talk to the snap
2. Fetching and adding the snap to state
3. Adding the permissions for the snap to do whatever it needs to do

We currently do not prompt for step 3 if the snap already has the permissions specified in its manifest. We should also not prompt during step 1 if the installer has the permission to access the snap being requested.

This will simply require checking if the permission already exists before requesting it in the `wallet_enable` implementation, by means of a new "hook" that calls the underlying `PermissionController` method / action.

**Comment by FrederikBolding** [comment]
Hmm, do we want to return the `permissions` that the DApp already has in this?

For now, I propose we add `hasAllPermissions` which can check multiple permissions at a time, but if we want to return the already granted permissions, we may also want to add a function for that?

```
if (await hasAllPermissions(Object.keys(requestPermissions))) {
      result.permissions = ?;
} else {
      result.permissions = await requestPermissions(requestedPermissions);
}
```

**Comment by FrederikBolding** [comment]
Also is it enough to check for the keys or do we need new functionality to check stuff like this? 🤔  
```
  "initialPermissions": {
    "snap_confirm": {},
    "eth_accounts": {
      "requiredMethods": [
        "eth_decrypt"
      ]
    }
  },
```
