### ISSUE TITLE
Consider graphing snap permissions

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#374]
Consider using a graph to visualize snap permissions. I.e. to determine which snaps have permission to talk to each other etc.

**Comment by rekmarks** [comment]
@FrederikBolding please expand on the benefits of this approach and suggest an implementation. It would be a considerable effort and we should have a strong justification for pursuing it.

**Comment by FrederikBolding** [comment]
> @FrederikBolding please expand on the benefits of this approach and suggest an implementation. It would be a considerable effort and we should have a strong justification for pursuing it.

This was a comment I noted down from the workshop in Amsterdam, not my own idea. But I think the general concern was that it'll be difficult to understand which snaps have permission to talk to each other without visualizing. Especially with key management snaps or other snaps that somehow manage secrets.

**Comment by ritave** [comment]
This shouldn't be a part of the extension. If the community would like to create a tool like that, I don't see a reason we wouldn't support them in their endeavour to get permission data.

Closing as wontfix
