### ISSUE TITLE
Look into potential issues with invoking multiple snaps at once

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#376]
A participant in the workshop found a weird issue when invoking multiple snaps at once. Opening this issue so I remember to debug this

**Comment by Aesthetic** [comment]
it _was_ weird

**Comment by FrederikBolding** [comment]
To reproduce: 

1. Clone `template-snap` and modify it to have a while loop inside `registerRpcMessageHandler`
2. Build and serve locally
3. Connect to the snap and click "send hello"
4. Now connect to https://metamask.github.io/template-snap/ and click "send hello" 
5. You are now in a bad state

**Comment by FrederikBolding** [comment]
This has been alleviated by #379, not sure if we want to close or not? 🤔

**Comment by rekmarks** [comment]
We definitely alleviated this, but we shouldn't close this until we've confirmed that the extension recovers within 60 minutes or something. Assigning to @bowensanders.

**Comment by bowensanders** [comment]
> We definitely alleviated this, but we shouldn't close this until we've confirmed that the extension recovers within 60 minutes or something. Assigning to @bowensanders.

I assume you mean 60 seconds or so? 
___
**Testing Report:**

I was able to replicate the breaking behavior on `develop`:
- first tested to make sure the template snap would connect and 'hello snaps' properly ☑️ 
- went through these steps to double check it's broken still:
1. loading the [infinite loop](https://github.com/MetaMask/template-snap/tree/infinite-loop) first
2. Click "send hello" on that snap (no response) 
3. loading the [live template](https://metamask.github.io/template-snap/) 
4. click "connect" (no response)
5. nothing seems to work with snaps after this until extension is reset (via manage extensions)

I tried multiple different sequences, and then repeated the above, and finally after waiting some time, I uninstalled the live template snap and tried to reinstall and run it. It gave a super interesting error:
<img width="482" alt="Screen Shot 2022-05-09 at 4 33 40 PM" src="https://user-images.githubusercontent.com/27023908/167515082-b481bf05-5220-49d7-98e1-b04277f0d3c2.png">

I don't know if the extension completely crashed before or not, but that does not seem to be happening, but still it appears to me that, on `develop` if you try to replicate the problem, it definitely stops snaps from installing and running properly.

On a whim, i decided to fire up the live test-snaps page and tried to install and run the bip-44 test and received this error: 
<img width="466" alt="Screen Shot 2022-05-09 at 4 38 09 PM" src="https://user-images.githubusercontent.com/27023908/167515402-f40daa66-9c0b-41e5-9c15-cb1852e4b25d.png">

Whatever the infinite loop snap does to the internal snaps mechanisms appears to persistently interfere with new snaps installations. 

If I can provide any more specific information to you regarding `background.html ` or anything else please let me know.

**Comment by bowensanders** [comment]
See BugReplay [here](https://app.bugreplay.com/#/shared/reports/2c86064c-9203-49d6-a5e8-15d1d5cc0c34)

**Comment by rekmarks** [comment]
@bowensanders can you repro this on the `skunkworks@0.12.0` branch?

**Comment by rekmarks** [comment]
@bowensanders please try to repro on `metamask-extension#develop` once `skunkworks@0.16.0` has been merged, and report results here.

**Comment by bowensanders** [comment]
Reproducing this requires me to refactor the test code to be in line with current skunkworks. Attempting this now.

**Comment by Montoya** [comment]
@bowensanders is this still an issue?

**Comment by bowensanders** [comment]
I have not been able to reproduce this issue.
I will close this.
