### ISSUE TITLE
Snap request timeouts while waiting for prompt confirmation

### ISSUE THREAD

**Issue by mpetrunic** [MetaMask/snaps-skunkworks#380]
I'm migrating this from: https://github.com/ChainSafe/filsnap/issues/130

Description:
If you invoke a snap method that displays a confirmation prompt to the user, the user could wait a bit before confirming after which it gets an error that the request timed out. 

An ideal solution would be if we could have no timeouts when there is a confirmation prompt waiting for user input. Alternatively, the promt should close automatically with an appropriate message (a timer in prompt would be a nice touch in that case).

**Comment by FrederikBolding** [comment]
Confirmations should not be shown for terminated snaps anymore: https://github.com/MetaMask/metamask-extension/issues/14494

This fix will be released in a future Flask release. 

This isn't perfect, but does solve the current UX issue - we should probably be more lax with timeouts when snaps are waiting for MM to do something, I will create a new issue for this.
