### ISSUE TITLE
Flask white screen

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps-skunkworks#405]
I seem to be able to reproduce it consistently now with these errors in the logs:

```
Error in RPC response: [object Object]
MetaMask - RPC Error: User rejected the request. [object Object]
Error: PortDuplexStream - disconnected
```

I try to connect from my snap (at the moment Flask is just hanging on the preloader) and then reject it twice. Subsequently I try to launch it from the browser chrome and just get a white screen.

If I restart Chrome I can see Flask again but it is still stuck on the preloader.

I am starting to suspect a problem with `localForage` but I need to re-install Flask now to continue with my snap development.

I have a video but can't upload it here because it exceeds 10MB; wish I had more information to help you diagnose this 🙏 

FYI, re-installing Flask fixes the problem.

Also see #363 where I reported a similar issue which probably has the same root cause.

**Comment by tmpfs** [comment]
Ok, so something strange just happened that might indicate that those error messages are a red herring.

I got the white screen and the extension manager shows that there are no errors in the logs!

Here is a video...

https://user-images.githubusercontent.com/238069/166092881-f4799feb-eb34-4cd0-bc41-795bbe10e2d0.mov

**Comment by DONOVAN7493** [comment]
HI @tmpfs I  suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by FrederikBolding** [comment]
@tmpfs Can you provide instructions to reproduce it? Is it just running https://github.com/LavaMoat/ecdsa-wasm/tree/snap?

**Comment by tmpfs** [comment]
@FrederikBolding, yes I am running that snap but there does not appear to be any steps to reproduce it at this stage - it happens intermittently. We need better diagnostics for what is happening in `background.html` when the extension boots so that next time it happens we can dig deeper into where it is hanging.

**Comment by rekmarks** [comment]
@tmpfs has this happened to you in recent memory? Any potential repro steps to share?

**Comment by tmpfs** [comment]
@rekmarks, no more information on this yet sorry. I have been focused on some p2p work so have not been running the Snap. Will update here if I learn anything new!

**Comment by rekmarks** [comment]
Thanks @tmpfs! We have been unable to reproduce this, and given the amount of changes made since this was initially reported, we will regard this as stale and close it. Please do let us know if this or any other problem comes up.
