### ISSUE TITLE
'WebAssembly.memory is not a constructor' error when running wasm snap

### ISSUE THREAD

**Issue by lsankar4033** [MetaMask/snaps-skunkworks#426]
I'm trying to run a snap that uses wasm code that uses `WebAssembly.memory` and run into the following error
![Screen Shot 2022-05-07 at 8 50 55 AM](https://user-images.githubusercontent.com/451947/167261890-18a24deb-a885-4f6c-ad55-a1897467b8b9.png)

Metamask version 10.14.1-flask.0

snap being tested is here: https://github.com/0xPARC/cabal/tree/main/snap (note that wasm is currently loaded from a URL: https://github.com/0xPARC/cabal/blob/main/snap/src/snark_utils/generate_proof.js#L9)

cc @ritave @FrederikBolding

**Comment by lsankar4033** [comment]
notably, it *works* with develop head (https://github.com/MetaMask/metamask-extension/commit/07da8ce58923cc3fc0959691c9f04c5b1312891e)

getting this released is crucial for us to launch/publicize cabal.xyz (0xPARC project that uses mm snap for snark proving) more widely. we'd love for users to not have to download a custom version of flask to try it

**Comment by FrederikBolding** [comment]
@lsankar4033 Yeah, this should be fixed in the next release of Flask. Flask is currently a bit behind the released skunkworks packages due to release troubles with the main extension. I'll keep this issue open until the fix is released.

**Comment by lsankar4033** [comment]
got it, thanks! any time estimate on when the next release will be cut? we'd like to put our blog post out on the 0xparc.org blog post right after it

**Comment by rekmarks** [comment]
@lsankar4033 we should ship later this week, I'll update here as soon as I have a better idea!

**Comment by FrederikBolding** [comment]
@lsankar4033 Sorry for the delay on this. This fix is included in Flask `10.15.0`, which was just released. Closing this now, let me know if you have any further issues!
