### ISSUE TITLE
Improve Snaps intro documentation

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-skunkworks#441]
Currently the marketing team is linking to the [intro page on the documentation site](https://docs.metamask.io/guide/snaps.html#what-is-snaps) whenever they talk about Snaps. It's the only entry point that exists until Snaps has its own landing page. 

The above-the-fold section could be improved with a strong opening statement, a compelling graphic and some buckets showcasing the example reference Snaps we already have (FilSnap, BTC Snap, Password Manager). 

Action items: 

1. @eriknson to query internally for examples of great documentation
2. @Montoya to survey our community devs for more insights into what was their entry point to Snaps and what do they like most in documentation 
3. @eriknson to sketch some graphic concepts that could be used on this page
4. @Montoya to update the above-the-fold section on this page

Very rough sketch of action item 4, from our Zoom call: 

![Screen Shot 2022-05-11 at 10.41.40 AM.png](https://images.zenhubusercontent.com/61fad535000896169845fff9/b7350b0d-1c9b-42d2-b107-fe0f18f3f0b4)

**Comment by Montoya** [comment]
#2 is done, see response here: https://github.com/MetaMask/snaps-skunkworks/discussions/442

For #4, if we have a mockup of what we want done, we can ask a dev to implement it. It will require some modification of the layout or a plugin to implement a custom content block.

**Comment by Montoya** [comment]
Current plan is to add a graphic to the Snap intro and close this task. The other changes will not be implemented. Instead, will focus on the Snaps landing page as the ideal intro to Snaps.

**Comment by eriknson** [comment]
We'll begin by updating / adding these sections;
- Snaps features (current and upcoming)
- Get started (ft. the new template-snap)
- Community
- Examples

Here are [suggested designs](https://www.figma.com/file/BuRbBnJFxu8JG6H5K4ayfr/Snaps-docs?node-id=1%3A5).

**Comment by Montoya** [comment]
Done!
