### ISSUE TITLE
Explore relaxing timeouts when snaps are waiting for response from the extension

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#444]
We should look into ways of "pausing" or otherwise relaxing the execution timeout of a snap when the snap is waiting for a response from the extension. This will also prevent the problem of having snaps time out while they are waiting for the user to accept or reject a confirmation

**Comment by rekmarks** [comment]
A simple solution to this could be specifying a set of methods that suspends the execution timeout until they return. If we do so, it should parameterized to the `SnapController`.

I'm curious to hear both what @FrederikBolding and @ritave think of such a solution given your work on timeouts and execution.

**Comment by ritave** [comment]
@rekmarks Was thinking of something even simpler. Just pause the timer until **any** Metamask `wallet.request` returns control back to Snap, no need for a whitelist.

**Comment by FrederikBolding** [comment]
> @rekmarks Was thinking of something even simpler. Just pause the timer until **any** Metamask `wallet.request` returns control back to Snap, no need for a whitelist.

Yeah, I agree. See the Slack thread for more context!

**Comment by rekmarks** [comment]
Alright, we can go with that. I'll create a new issue for the implementation.
