### ISSUE TITLE
Implement source mapping for the Snaps transform and our bundler plugins

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps-skunkworks#471]
The transforms we apply to snaps are not source-mapped. For example, bundling a snap with Rollup using the Rollup plugin results in the following warning:

```
./src/snap.ts → ./dist/snap.js...
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "@metamask/rollup-plugin-snaps") should generate accompanying sourcemaps
created ./dist/snap.js in 530ms
```

If we want to have source maps for snaps, we need to implement source mapping for:
- [ ] `@metamask/snaps-cli`
- [ ] `@metamask/rollup-plugin-snaps`
- [ ] `@metamask/snaps-browserify-plugin`
- [ ] `@metamask/snaps-webpack-plugin`

**Comment by FrederikBolding** [comment]
I guess we should just regenerate the source map if possible? But I am also unsure if they are useful at all when executing in SES.

**Comment by rekmarks** [comment]
I have no idea how source mapping works, but I imagine that it's more complicated than turning some flag on and off. @Mrtenz do you have any idea how difficult this would be? I imagine it reduces to "take the snap source code, find its source maps, run the transform, regenerate the sourcemaps"?

**Comment by rekmarks** [comment]
After doing some research, I've confirmed that it in all likelihood does reduce to this. If someone has experience with source mapping feel free to advocate for the prioritization of this issue, but otherwise this is going in the ice box for right now.

**Comment by Mrtenz** [comment]
This might be possible after #583 is merged. We can generate a source map using `@babel/generator`.
