### ISSUE TITLE
Timer handle should not reach code in a Compartment

### ISSUE THREAD

**Issue by naugtur** [MetaMask/snaps-skunkworks#476]
This is what the handle returned from setTimeout looks like in Node.js

![Screenshot_2022-05-18_23-26-57](https://user-images.githubusercontent.com/509375/169158748-2ccd4e35-80aa-4c8e-bc7f-3e813c6ff756.png)

This will no longer be an issue under #475

**Comment by ritave** [comment]
Fixed by #485  and #483
