### ISSUE TITLE
Remove functions from `SnapController` constructor

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#484]
Instead of passing in functions in the `SnapController` constructor, we should use the messaging system.

**Comment by rekmarks** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/484?planning-poker) with ZenHub @FrederikBolding
