### ISSUE TITLE
Examples don't auto-bump dependencies when doing a new release

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#489]
When doing a new release we bump dependencies in each of the Yarn workspaces to match the newest versions of the other workspaces. This doesn't work for all examples and therefore results in CI failure, see: https://github.com/MetaMask/snaps-skunkworks/pull/487

**Comment by rekmarks** [comment]
@Mrtenz @FrederikBolding is this fixed?

**Comment by FrederikBolding** [comment]
@rekmarks I think we are waiting for a release!

**Comment by FrederikBolding** [comment]
Once the action is released we can bump it in skunkworks and fix the issue I believe. @Mrtenz correct me if I am wrong

**Comment by rekmarks** [comment]
This was on my plate this entire time, I had just forgotten it. `action-create-release-pr@1.4.0` has been released, and since we target the `v1` tag in this repo, that's what we'll be using now. This issue is resolved.
