### ISSUE TITLE
Explore APIs needed to be exposed for hardware wallets

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#498]
Likely to be `WebUSB`, `WebHID` etc.

**Comment by HarishRocks** [comment]
Even I am really looking forward to it.

**Comment by FrederikBolding** [comment]
Example code:
```
/* eslint-disable no-case-declarations */
const { DEFAULT_ETH, LedgerWallet } = require('@mycrypto/wallets');

module.exports.onRpcRequest = async ({ request }) => {
  switch (request.method) {
    case 'hello':
      const ledger = new LedgerWallet();
      const instance = await ledger.getWallet(DEFAULT_ETH, 0);
      return instance.signMessage(request.params[0]);
    default:
      throw new Error('Method not found.');
  }
};

```

**Comment by rekmarks** [comment]
We should investigate how the extension overcomes this in its existing hardware wallet integrations. Maybe @darkwing can shed some light.

**Comment by FrederikBolding** [comment]
To support hardware wallets as snaps we can expose `WebHID` and `WebUSB` via globals. However, we would need to initialize the  hardware connection in the MetaMask extension by allowing the user to click a button, triggering a user gesture outside of a snap. After that is done the connection should be available to snaps. 

This is the same way the extension is currently doing it. While we are still running snaps in iframes, this seems like the only option.
