### ISSUE TITLE
Add TypeScript flag to `mm-snap init`

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#513]
We should allow users to easily start using TypeScript by expanding the init command.

This may be resolved by creating a TypeScript template-snap repository and updating the `mm-snap init` logic to use the source from that for initialization. For now, we should generate both a `init-template.json` for vanilla JS and TypeScript, and use those for the initialization. 

This example could be used as a reference: https://github.com/MetaMask/snaps-skunkworks/tree/main/packages/examples/examples/typescript

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/513?planning-poker) with ZenHub @FrederikBolding @hmalik88 @david0xd @GuillaumeRx @Mrtenz @ritave

**Comment by FrederikBolding** [comment]
Done in #546
