### ISSUE TITLE
Handle non-terminal errors from plugins

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#54]
We should handle non-terminal errors from plugins, i.e. errors that bubble up to the parent realm but do not stop the plugin from executing, for example errors thrown in a `setTimeout` handler.

These errors should be logged such that they can be reported to plugin developers.

**Comment by shanejonas** [comment]
fixed in #88 

although when we talked to the agoric guys, the advice was to shut down the plugin in response to non-terminal or out of band errors
