### ISSUE TITLE
Add automated npm publishing via `action-npm-publish`

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#561]
We have a home-grown action named `action-npm-publish` that we should add to our `publish-release` workflow in order to publish skunkworks automatically to npm. @rickycodes has some pending (merged?) changes that makes the action functional for monorepos. He also has a helpful guide [here](https://www.notion.so/Automatic-NPM-Publishing-24e52be61e8742d3bfc465073339beba).

@rickycodes, any additional context to share for what we have to do in order to adopt this action? Is it ready to go?

**Comment by FrederikBolding** [comment]
Looks like it's still pending: https://github.com/MetaMask/action-npm-publish/pull/5

**Comment by FrederikBolding** [comment]
Closed by #626
