### ISSUE TITLE
Limit Snaps storage to ensure they can't break Metamask storage

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-skunkworks#571]
Currently, Snaps share the same `localstorage` space along with the main extension. If a bad actor decides to fill the all the storage, the main extension can become unusable.

**Comment by FrederikBolding** [comment]
Related: https://github.com/MetaMask/snaps-skunkworks/issues/209

There is code I've written somewhere for this to determine the size of a JSON object.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/571?planning-poker) with ZenHub @david0xd @FrederikBolding @GuillaumeRx @hmalik88 @Mrtenz @ritave

**Comment by FrederikBolding** [comment]
Reopening until we use the updated code in skunkworks. cc @david0xd
