### ISSUE TITLE
Remove WebWorker implementation

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#578]
Remove the WebWorker implementation. The tests that use it should be moved to a Node.js execution environment (https://github.com/MetaMask/snaps-skunkworks/pull/523). Furthermore, we should stop using Electron to run tests and use JSDom for all tests.

**Comment by rekmarks** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/578?planning-poker) with ZenHub @FrederikBolding
