### ISSUE TITLE
`yarn install` doesn't reset dependencies to their original state

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#584]
If you modify a dependency and run `yarn install` or `yarn setup` the modifications to the dependency stick around. This seems unexpected, perhaps a Yarn 3 issue?

**Comment by Mrtenz** [comment]
This seems to be intentional in Yarn 3, as you shouldn't modify dependencies in `node_modules` directly. To patch a package, use [`yarn patch`](https://yarnpkg.com/cli/patch). In any case, I don't think this is a bug in `snaps-skunkworks`.
