### ISSUE TITLE
Set limit for number of concurrent snaps

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#59]
Per #56, we need some kind of limit on the concurrent number of snaps. We need to arrive at this number experimentally.

**Comment by Gudahtt** [comment]
This should also encompass the work involved in handling the situation when we reach the limit of concurrent snaps (e.g. do we reject new snap requests? Queue them up? How large of a queue?)

**Comment by ritave** [comment]
We've [run a benchmark on `ritave/onslaught` branch](https://github.com/MetaMask/snaps-skunkworks/tree/ritave/onslaught) and concluded that iframes can run 100+ snaps at the same time without any hiccups.
