### ISSUE TITLE
Allow snaps to be rolled back

### ISSUE THREAD

**Issue by hmalik88** [MetaMask/snaps-skunkworks#618]
We need to have a rollback mechanism in place to complete the update snap feature set.

Some of the feature work is outlined in [issue # 223](https://github.com/MetaMask/snaps-skunkworks/issues/223):

>   * We should provide a rollback mechanism. As the new version is installed and booted, we should take a snapshot of the existing state (if the snap has state management) and permissions and the old snap as it exists in `SnapController` state. We should retain the old snap in state for a configurable period of time, so that we can give the user the option to roll back if they want to.
>     
>     * We should also roll back automatically if the new snap fails to start or crashes after startup.
> 
> There are some outstanding questions to solve:
> 
> * What happens when the permissions differ between snap versions?
>   
>   * Permissions added by a new version are easy enough, but permissions _removed_ by a new version are more difficult to handle. Note that we want to let snaps request permissions dynamically, and that the rollback mechanism must take our solution into account.
>   * If the PermissionController's interface doesn't support our needs here, we can modify it.
> * How do we detect a crash on startup? Do we run the snap before letting it communicate with the outside world?

There's some additional points to be made and questions to be raised:

* How many versions of a snap do we need to keep?

     * For now we can simply rollback to the previously installed version of a snap. In the future, we can let people choose multiple versions they want to keep as rollbacks. It would be possible by doing away with the default rollback of the previous version and incorporating a "cache previous version of snap" option into the update flow. We can then decide on a limit of versions per snap.
     * What happens when you rollback to a previous version? Do we store a snapshot of the state we rolled back from as well? In other words will we be snapshotting both updates and rollbacks?

* How long do we want the default retention period to be for the rolled back snap?

* There will be UI work needed extension side for the user triggered rollback. This will also include updating the view snap component to include some control to set the number of days you'd like to retain the snap and a button to roll it back (do we want this in the snaps settings card list view as well?) See extension [issue # 15203](https://github.com/MetaMask/metamask-extension/issues/15203) -- [THIS IS A V2 FEATURE]

* Do we want to send some sort of notification if the snap is rolled back automatically on start up?

* How do we want to determine if a snap is crashing on startup? Can we potentially just listen for errors thrown in the execution environment and then just stop and rollback the snap?

* We should have a `snapRolledBack` event to trigger certain actions in the extension i.e. update current metadata, track metrics.

**Comment by ritave** [comment]
We've decided that rollbacks are not necessary in practice. Most of the apps in the world don't have rollback and don't break in practice.
