### ISSUE TITLE
Consider TypeScript compilation target

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#624]
We are seeing a few Sentry errors in Flask coming from this:
https://github.com/MetaMask/snaps-skunkworks/blob/main/packages/controllers/src/services/iframe/IframeExecutionService.ts#L34

With the error being:
```
SyntaxError: Unexpected token .
```

This seems to be happening on older browsers and as such is likely because of our `ES2020` TypeScript compilation target. We should decide whether we want to support these older browsers or not.

**Comment by Gudahtt** [comment]
The other options would be to increase the minimum supported browsers, or to transpile this library during the build process.

**Comment by FrederikBolding** [comment]
> We could also temporarily decrease the TypeScript compilation target of this package until we decide whether we want to increase the requirements for supported browsers in the extension.

We ended up doing this, but may want to bump back to ES2020 in the future when possible.

**Comment by rekmarks** [comment]
A future minimum version change will likely stem from efforts occurring via the extension, so I will now close this issue.
