### ISSUE TITLE
Terminate idle and/or misbehaving snaps

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#63]
Per #56 and #62, we should continually monitor running snaps, and terminate them when:
- [x] they've been idle for a certain period of time (pulling a number out of a hat, on the order of 2 < 10 **minutes**)
- [x] they and/or their workers aren't responding to health checks for a certain period of time (on the order of 5 - 10 **seconds**)

**Comment by Natalona** [comment]
[smart chain-testent TRST ](MetaMask)
