### ISSUE TITLE
Serve needs CORS

### ISSUE THREAD

**Issue by compojoom** [MetaMask/snaps-skunkworks#635]
Hi,
I described my problem in the following discussion: https://github.com/MetaMask/snaps-skunkworks/discussions/633

I built a snap from the template: https://github.com/MetaMask/template-snap
But I cannot get it to work. 
After investigating why the connect doesn't bring the second prompt it turned out that the browser is blocking the request to fetch http://localhost:8080/snap.manifest.json

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/snap.manifest.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

I'm surprised that nobody has reported that?

The solution in my case was to add 
```
{
                            key: 'Access-Control-Allow-Origin',
                            value: '*',
                        }
```
over here:
https://github.com/MetaMask/snaps-skunkworks/blob/main/packages/cli/src/cmds/serve/serveHandler.ts#L29

Anyone who knows the code better - any ideas what's going on here?

How are you guys developing snaps locally?

**Comment by Mrtenz** [comment]
I'm not able to reproduce the issue. I tried running the snap from [the repository you linked](https://github.com/compojoom/mm-snap-trustlines), and everything runs fine in Google Chrome. Which browser are you using?

**Comment by compojoom** [comment]
I'm using Firefox Developer Edition: 103.0b8

**Comment by compojoom** [comment]
@Mrtenz well, yes! It works with chrome!

**Comment by FrederikBolding** [comment]
> @Mrtenz well, yes! It works with chrome!

Oh, interesting! So this is a Firefox specific issue?

**Comment by compojoom** [comment]
Yes, seems so. I'm currently trying to figure out why firefox is complaining about cors and chrome not.

**Comment by compojoom** [comment]
I compared the requests that firefox and chrome does. The only substantial difference I can see is in the request header origin. 
Firefox sets the origin to `moz-extension://id-of-extension` where chrome just doesn't send an origin.

I had a look at the other requests that metamask does and the reponses either have `access-control-allow-origin: *` or `access-control-allow-origin: moz-extension:id-of-extension`.

I think that setting it to `*` is fine, but we could theoretically also set it to the value that comes as request header.
