### ISSUE TITLE
Add `wallet_getBip32Entropy` restricted method

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#643]
Some forms of key derivation necessitate deviations from the [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) standard, for example SegWit ([BIP-49](https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki)) and native SegWit ([BIP-84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki)) Bitcoin accounts. Since we shipped [`@metamask/key-tree@4.0.0`](https://github.com/MetaMask/key-tree/releases/tag/v4.0.0), we are able to provide entropy for arbitrary [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki] paths. We should leverage the full capabilities of this package and ship one or more restricted methods supporting these use cases.

The method could be named `wallet_getBip32Entropy` and modeled on the existing `getSlip44Entropy` method, with the following differences:
- The user should be able to specify one or more arbitrary BIP-32 paths using this permission, of arbitrary depths.
  - ~We could go with a wildcard implementation and do something like `wallet_getBip32Entropy_m/84'/0'`~
  - We ~could~ should go with some kind of caveat format where the permission is parameterized in the snap manifest, like we plan to do with snap keyrings.
- We should make sure that the path `m/44'` cannot be requested, and we should in general maximally attenuate the permission while ensuring that it's still flexible enough for all/the vast majority of BIP-32 use cases.

**Comment by aaronisme** [comment]
I think this method is really needed since many bitcoin users are not using the 44 as the purpose. like BIP-49 and BIP-84

**Comment by aaronisme** [comment]
For implementation, I suggest adding the bip32 path as the params. Like

```
 wallet.request({
  method: 'wallet_getBip32Entropy',
  params: [84', 0', 0']
});
```

**Comment by FrederikBolding** [comment]
> For implementation, I suggest adding the bip32 path as the params. Like
> 
> ```
>  wallet.request({
>   method: 'wallet_getBip32Entropy',
>   params: [84', 0', 0']
> });
> ```

The problem with that is that we likely want to have as restrictive permissions as possible. We don't want snaps to be able to request arbitrary entropy without having user permission for that specific derivation path.

**Comment by FrederikBolding** [comment]
We could do something like this? This would just take `snap_getBip32Entropy_84'/0'`.

cc @Mrtenz 

```
import {
  PermissionSpecificationBuilder,
  PermissionType,
  RestrictedMethodOptions,
  ValidPermissionSpecification,
} from '@metamask/controllers';
import { ethErrors } from 'eth-rpc-errors';
import { JsonSLIP10Node, SLIP10Node } from '@metamask/key-tree';
import { NonEmptyArray } from '@metamask/utils';

const methodPrefix = 'snap_getBip32Entropy_';
const targetKey = `${methodPrefix}*` as const;

export type GetBip32EntropyMethodHooks = {
  /**
   * @returns The mnemonic of the user's primary keyring.
   */
  getMnemonic: () => Promise<string>;

  /**
   * Waits for the extension to be unlocked.
   *
   * @returns A promise that resolves once the extension is unlocked.
   */
  getUnlockPromise: (shouldShowUnlockRequest: boolean) => Promise<void>;
};

type GetBip32EntropySpecificationBuilderOptions = {
  allowedCaveats?: Readonly<NonEmptyArray<string>> | null;
  methodHooks: GetBip32EntropyMethodHooks;
};

type GetBip32EntropySpecification = ValidPermissionSpecification<{
  permissionType: PermissionType.RestrictedMethod;
  targetKey: typeof targetKey;
  methodImplementation: ReturnType<typeof getBip32EntropyImplementation>;
  allowedCaveats: Readonly<NonEmptyArray<string>> | null;
}>;

/**
 * The specification builder for the `snap_getBip32Entropy_*` permission.
 * `snap_getBip32Entropy_*` lets the Snap control private keys for a particular
 * BIP-32 coin type.
 *
 * @param options - The specification builder options.
 * @param options.allowedCaveats - The optional allowed caveats for the permission.
 * @param options.methodHooks - The RPC method hooks needed by the method implementation.
 * @returns The specification for the `snap_getBip44Entropy_*` permission.
 */
const specificationBuilder: PermissionSpecificationBuilder<
  PermissionType.RestrictedMethod,
  GetBip32EntropySpecificationBuilderOptions,
  GetBip32EntropySpecification
> = ({
  allowedCaveats = null,
  methodHooks,
}: GetBip32EntropySpecificationBuilderOptions) => {
  return {
    permissionType: PermissionType.RestrictedMethod,
    targetKey,
    allowedCaveats,
    methodImplementation: getBip32EntropyImplementation(methodHooks),
  };
};

export const getBip32EntropyBuilder = Object.freeze({
  targetKey,
  specificationBuilder,
  methodHooks: {
    getMnemonic: true,
    getUnlockPromise: true,
  },
} as const);

const ALL_DIGIT_REGEX = /^\d+$/u;

/**
 * Builds the method implementation for `snap_getBip32Entropy_*`.
 *
 * @param hooks - The RPC method hooks.
 * @param hooks.getMnemonic - A function to retrieve the Secret Recovery Phrase of the user.
 * @param hooks.getUnlockPromise - A function that resolves once the MetaMask extension is unlocked and prompts the user to unlock their MetaMask if it is locked.
 * @returns The method implementation which returns a `JsonSLIP10Node`.
 * @throws If the params are invalid.
 */
function getBip32EntropyImplementation({
  getMnemonic,
  getUnlockPromise,
}: GetBip32EntropyMethodHooks) {
  return async function getBip32Entropy(
    args: RestrictedMethodOptions<void>,
  ): Promise<JsonSLIP10Node> {
    const rawPath = args.method.substr(methodPrefix.length);
    const path = rawPath.split('/');

    if (path.length !== 2) {
      throw ethErrors.rpc.methodNotFound({
        message: `May only define a path of length 2`,
      });
    }

    // Extract indices from strings
    const nonValidatedIndices = path.map((p) => p.split("'")[0]);

    nonValidatedIndices.forEach((index) => {
      if (!ALL_DIGIT_REGEX.test(index)) {
        throw ethErrors.rpc.methodNotFound({
          message: `Invalid index in path: ${index}`,
        });
      }
    });

    const validatedIndices = nonValidatedIndices.map((i) => Number(i));

    if (validatedIndices[0] === 44) {
      throw ethErrors.rpc.methodNotFound({
        message: `44 is not allowed as the first index of the path. Please use snap_getBip44Entropy_*`,
      });
    }

    await getUnlockPromise(true);

    // Always harden indices
    const node = await SLIP10Node.fromDerivationPath({
      derivationPath: [
        `bip39:${await getMnemonic()}`,
        `bip32:${validatedIndices[0]}'`,
        `bip32:${validatedIndices[1]}'`,
      ],
      curve: 'secp256k1',
    });

    return node.toJSON();
  };
}

```

**Comment by rekmarks** [comment]
@Mrtenz I'm not sure if we're saying the same thing, but my point is that:
- We will never give a snap index 0, i.e. `m`.
- We also don't want to permit `m/44'` (an instance of index 1) because that of course grants access to all BIP-44 / SLIP-44 keys. 
- Other standardized purpose / index 1 paths should probably also be forbidden, by POLA.

So I'm suggesting we should have some kind of minimum depth and/or forbid certain paths outright. Beyond that the caller should be able to get however many indices they want.
