### ISSUE TITLE
Add ControllerMessenger events and actions to SnapController

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-skunkworks#65]
The `SnapController` should use `ControllerMessenger` events and actions to their full effect. Currently, it doesn't define any actions or events in addition to `stateChange`.

This is a refactoring ticket that we should undertake after the permissions controller changes are landed.

**Comment by rekmarks** [comment]
Blocked by #28.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/65?planning-poker) with ZenHub @Gudahtt @jknoll @shanejonas

**Comment by rekmarks** [comment]
Note: This is blocked by the new permissions system.

**Comment by ritave** [comment]
Events were added here https://github.com/MetaMask/snaps-skunkworks/pull/162
