### ISSUE TITLE
Integrate Transaction Insight into the MetaMask Extension UI

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-skunkworks#655]
Following https://github.com/MetaMask/snaps-skunkworks/pull/642 we should integrate the transaction insight API into the extension UI.

**Comment by eriknson** [comment]
Here's the current [design for TX Insights](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=91%3A3192). Happy to sync on it; just reach out to me or leave comments directly in the Figma.
