### ISSUE TITLE
Add support for FormData

### ISSUE THREAD

**Issue by Julink-eth** [MetaMask/snaps-skunkworks#680]
It'd be nice to be able to use FormData directly from the snap as currently it is not possible.
I was able to get around it by creating a new object this way :

`const formDataObj = new Object({ data: value }) as any;`

Then calling fetch :

```
const result = await fetch(url.toString(), {
  method: 'POST',
  body: formDataObj,
});
```

**Comment by ritave** [comment]
Sorry for late response. When the above PR gets merged, the next Flask release should have your fix.

You can observe release changes in the metamask-extension changelog with `[FLASK]` tag - https://github.com/MetaMask/metamask-extension/blob/develop/CHANGELOG.md

**Comment by Julink-eth** [comment]
Awesome thank you for letting me know !

**Comment by ritave** [comment]
The implementation work showed that there's a lot of hidden complexity. We need to support Node v16, which doesn't have `FormData`. We tried using ponyfills, but the best one is an ESM module, that's not easily compatible with the rest of our ecosystem.

That's too much implementation and maintenance work for something that can be replaced with a simple JS object.

Marking as wontfix.
