### ISSUE TITLE
Add method for retrieving public key

### ISSUE THREAD

**Issue by andyv09** [MetaMask/snaps-skunkworks#688]
It would be nice to have a method for retrieving account public key without the need to use snap_getBip44Entropy*, or exposing private keys. 

This can be currently done by signing a message and then recovering public key from there, which is not the easiest, nor most intuitive way.

**Comment by FrederikBolding** [comment]
What's the use case? Do you need to verify that the user controls a specific address or just need _any_ public key?

**Comment by andyv09** [comment]
We're using public key to generate DIDs with DID methods capable of expressing secp256k public key. We also need to verify that the user controls the specific address.

**Comment by FrederikBolding** [comment]
Hmm, would a function similar to `snap_getBip32Entropy` be suitable (without exposing private keys)? Where you can specify a curve and derivation path and then get the public key of that node returned?

I.e.
```
const publicKey = await  wallet.request({
  method: 'snap_getBip32PublicKey',
  params: {
    // Must be specified exactly in the manifest
    path: ['m', "44'", "3'", "0'", "0", "0"],
    curve: 'secp256k1',
  },
});
```

cc @Mrtenz

**Comment by Mrtenz** [comment]
#729
