### ISSUE TITLE
Remove deployed template snap

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-skunkworks#727]
We're not updating the example template snap anymore and it has been broken for a while. People are getting confused when using documentation. We need to either remove it or keep updating it.

- [x] Remove all links from documentation to `https://metamask.github.io/template-snap/`
- [x] Deprecate `https://www.npmjs.com/package/@metamask/template-snap`
- [x] Remove `https://metamask.github.io/template-snap/`
- [ ] Archive repo

**Comment by FrederikBolding** [comment]
Related: https://github.com/MetaMask/template-snap/issues/41

**Comment by Montoya** [comment]
Will update documentation as part of other documentation task

**Comment by Montoya** [comment]
Final step, assigned to Erik Marks, to remove the GitHug pages site for the old template-snap and archive the repository!

**Comment by ritave** [comment]
We've decided not to archive the repo continue maintaining it. I've taken the GitHub page down.
