### ISSUE TITLE
improvements on permissions of `snap_getBip32Entropy`

### ISSUE THREAD

**Issue by BeroBurny** [MetaMask/snaps-skunkworks#747]
Did take some time to test the new feature `snap_getBip32Entropy` as needed for one snap we are currently building, and found out that to request entropy you need to use the same depth (and index) as specified in `snap.manifest.json` if you go deeper you request will fail as is not specified in the manifest. 

Let's take examples

`snap.manifest.json`
``` json
"snap_getBip32Entropy": [
  {
    "path": [
      "m",
      "44'",
      "461'",
    ],
    "curve": "secp256k1"
  },
]
```
We specified permission for a deep of 2 and now we want to get entropy for it

``` ts
await wallet.request({
  method: 'snap_getBip32Entropy',
  params: {
    path: ["m", "44'", "461'"],
    curve: 'secp256k1',
  },
});
```
work fine but let's give a case we want to specific account at index 3
``` ts
await wallet.request({
  method: 'snap_getBip32Entropy',
  params: {
    path: ["m", "44'", "461'", "3'"],
    curve: 'secp256k1',
  },
});
```
this will fail with an error for not authorized to use it, and there is no sense as we already have the permission of a parent.

**Comment by Mrtenz** [comment]
This is a good point, I hadn't thought about it before. Right now you can use `key-tree` to derive children of the node. See the docs [here](https://github.com/MetaMask/metamask-docs/blob/ad84f87f4d8c25694b5a77718b4c87e03e46f9b9/docs/guide/snaps-rpc-api.md#example-6) for an example.

I'll submit a PR to change this soon!
