### ISSUE TITLE
Auto generate permissions requests from static analysis

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/snaps-skunkworks#79]
Builds on MetaMask/snaps-skunkworks#78:

Once we can generate a list of required globals by closing MetaMask/snaps-skunkworks#78, we have two additional ways we can act:

- Warn the developer about globals that are strictly prohibited, suggesting strategies of refining their dependency graph around that API.
- Offer to automatically add this API to the requested permissions object (if it isn't already added to this object).

These can be interactive prompts from the `build` command, and if done right, would result in a perfectly working, consent-requesting plugin right out of the build, regardless of the authority that the dependency tree required.

**Comment by ritave** [comment]
Permissions now come with caveats ([for example keyring permissions specify their chain support](https://github.com/MetaMask/SIPs/blob/main/SIPS/sip-2.md#manifest)), which we could not automatically detect during build time.

Spending a lot of time for a tool that only solves the issue sometime is probably not something we'd like to spend the time on.
