### ISSUE TITLE
OnTransaction not firing

### ISSUE THREAD

**Issue by mindofmar** [MetaMask/snaps-skunkworks#798]
The transaction popup works fine, but nothing ever gets logged from `onTransaction`. Any thoughts on why this may be?

**Environment**
I'm running the latest Flask build from https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/28322/workflows/b7b372fa-6f21-415a-9b42-47ae28f46263/jobs/734644/artifacts

**Code**
in my `index.ts` file I have:
```
export const onTransaction: OnTransactionHandler = async ({
  transaction,
  chainId,
}) => {
  console.log(transaction);

  const insights = transaction;
  return { insights };
};
```

In my `index.html` I have the following 3 functions hooked up to buttons:
    `
    let from = '';

    async function connect () {
      await ethereum.request({
        method: 'wallet_enable',
        params: [{
          wallet_snap: { [snapId]: {} },
        }]
      })
    }

    async function requestAccounts() {
        const response = await ethereum.request({
          method: 'eth_requestAccounts',
          params: [snapId, {
            method: 'request'
          }]
        })
        from = response[0];
    }

    const transactionParameters = {
        from: '0xa4c1c9C2068a9940c433b3246613e741EdaF7639',
        to: '0x87Ae0C7900A599a6E980A576D975b5Ce8a79Ac9c',
        data: '0x2e1a7d4d0000000000000000000000000000000000000000000000000000000011e1a300',
        value: '0x0',
      };

    async function sendTransaction() {
        try {
          const response = await ethereum.request({
            method: 'eth_sendTransaction',
            params: [transactionParameters]
          })
        } catch (e) {
          console.log(e);
        }
    }`

Snap.manifest.json:
```
  "initialPermissions": {
    "endowment:transaction-insight": {},
    "snap_notify": {},
    "snap_confirm": {}
  },
```

**Comment by FrederikBolding** [comment]
Just to clarify before troubleshooting further, the `onTransaction` export is currently only triggered once you click and view the snap transaction insights tab in the transaction popup. Are you doing that?

**Comment by mindofmar** [comment]
Thank you @FrederikBolding I did not realize that's where the lifecycle of the snap started. After some testing it is working as a expected.

**Comment by ritave** [comment]
@Montoya Do you have some time to document that behaviour in the docs.metamask.io please?
